### ISSUE TITLE
.rosinstall no longer exists

### ISSUE THREAD

**Issue by Kanazawanaoaki** [knorth55/coral_usb_ros#12]
merge coral_usb_ros/fc.rosinstall in
https://github.com/knorth55/coral_usb_ros/blob/master/README.md#install-edge-tpu-dependencies no longer exists.
should we use `.travis.rosinstall.meloidc` ????

Cc: @k-okada

**Comment by knorth55** [comment]
hmm,
it exists in master branch.

**Comment by knorth55** [comment]
you mean this file, right? https://github.com/knorth55/coral_usb_ros/blob/master/fc.rosinstall

**Comment by k-okada** [comment]
sorry this is my misunderstanding. we overlooked that file.

**Comment by knorth55** [comment]
OK, thank you.
