### ISSUE TITLE
stuck at the ROS installation step

### ISSUE THREAD

**Issue by LevineYang** [knorth55/coral_usb_ros#8]
Hi, Shingo, amazing for beginner with coral usb or coral board.
Now I am using the coral board for autonomous vehicle, but I am stuck at the first step - install ROS on coral board, I followed the tutorial here "http://wiki.ros.org/Installation/UbuntuARM", but fails. 
Could you please give me some hints about how to successfully install ROS on coral board, thank you very much!

**Comment by knorth55** [comment]
Thank you for your issue.
Unfortunately, I haven't tried Coral Dev Board yet.
So, I do not know how to install ROS on Coral Dev Board.

**Comment by knorth55** [comment]
Please reopen if you still have this problem
